# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: blog@munimdibosh
email: abdulmunim.buet@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Periodic vomit of my consumed knowledge. I take React, Redux, Javascript,
  AngularJS, NodeJS, Python, ObjectiveC and you name it! So, don't be surprised
  if it's smelly!
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://munimdibosh.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: munimdibosh
github_username:  dibosh

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# exclude: [vendor]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
