title: blog@munimdibosh
email: abdulmunim.buet@gmail.com
description:
  Periodic vomit of my consumed geekiness. I take React, Redux, Javascript,
  AngularJS, NodeJS, Python, ObjectiveC and anything that's enough to tinker my
  programming hunger! So, don't be surprised if it's smelly sometimes!
baseurl: /blog
url: 'http://munimdibosh.me'
twitter_username: munimdibosh
github_username: dibosh
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
